BasicDotNetApp/Models/ErrorViewModel.cs
namespace BasicDotNetApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BasicDotNetApp/Models/Item.cs
using System.ComponentModel.DataAnnotations;

namespace BasicDotNetApp.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        public string Borrower { get; set; }
        public String Lender { get; set; }
        public String ItemName { get; set; }

    }
}

BasicDotNetApp/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;

namespace BasicDotNetApp.Controllers
{
    public class AppointmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            return Ok("Detail of ID: " + id);
            //Hello there world!
        }
    }
}

BasicDotNetApp/Controllers/HomeController.cs
using BasicDotNetApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BasicDotNetApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BasicDotNetApp/Controllers/ItemController.cs
using BasicDotNetApp.Data;
using BasicDotNetApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BasicDotNetApp.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ItemController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Item> objList = _db.Items;
            return View(objList);
        }
        public IActionResult Create()
        {
            return View();
        }
    }
}

BasicDotNetApp/Views/Appointment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Appointments</h1>

BasicDotNetApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BasicDotNetApp/Views/Item/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create new Item";
}
@model IEnumerable<BasicDotNetApp.Models.Item>

<h1 class="text-primary text-center">
    Create a new Item here
</h1>

BasicDotNetApp/Views/Item/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<BasicDotNetApp.Models.Item>

<h1 class="text-center">Index - Items</h1>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrowed Items list</h2>
        </div>
        <div class="col-6">
            <a class="text-primary" asp-controller="Item" asp-action="Create">Create new item</a>
        </div>
    </div><br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th scope="col">Item Name</th>
                    <th scope="col">Borrwer</th>
                    <th scope="col">Lender</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td width="30%">@item.ItemName</td>
                        <td width="30%">@item.Borrower</td>
                        <td width="30%">@item.Lender</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No items created yet!</p>
    }
</div>

BasicDotNetApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BasicDotNetApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BasicDotNetApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BasicDotNetApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Items</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BasicDotNetApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>